apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-node-app-{{COLOR}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-node-app
      track: {{COLOR}}
  template:
    metadata:
      labels:
        app: react-node-app
        track: {{COLOR}}
    spec:
      containers:
      - name: app
        image: {{IMAGE}}
        ports:
        - containerPort: 8000
        env:
        - name: SPANNER_DB_URI
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: SPANNER_DB_URI
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
