apiVersion: v1
kind: Service
metadata:
  name: react-node-app-{{COLOR}}-service
spec:
  type: LoadBalancer
  selector:
    app: react-node-app
    track: {{COLOR}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
